version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
    networks:
      - web
    restart: always

  site1:
    image: httpd:alpine
    container_name: site1
    networks:
      - web
    environment:
      - VIRTUAL_HOST=site1.local
    restart: always

  site2:
    image: nginx:alpine
    container_name: site2
    networks:
      - web
    environment:
      - VIRTUAL_HOST=site2.local
    restart: always

networks:
  web:
    driver: bridge
